# tasks file for supervisor
---
- name: install (pip) dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: supervisor_pip_dependencies
  tags: [configuration, supervisor, supervisor-pip-dependencies]

- name: install supervisor (specific version)
  pip:
    name: supervisor
    version: "{{ supervisor_version }}"
  when: "supervisor_version != 'latest'"
  tags: [configuration, supervisor, supervisor-install]

- name: install supervisor (latest version)
  pip:
    name: supervisor
    state: "{{ supervisor_version }}"
  when: "supervisor_version == 'latest'"
  tags: [configuration, supervisor, supervisor-install]

- name: create directories
  file:
    path: "{{ item | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ supervisor_configuration_file }}"
    - "{{ supervisor_unix_http_server_file }}"
    - "{{ supervisor_supervisord_logfile }}"
    - "{{ supervisor_supervisord_pidfile }}"
    - "{{ supervisor_supervisord_childlogdir }}"
    - "{{ supervisor_include }}"
  tags: [configuration, supervisor, supervisor-directories]

- name: update configuration file - /etc/supervisor/supervisord.conf
  template:
    src: etc/supervisor/supervisord.conf.j2
    dest: "{{ supervisor_configuration_file }}"
    owner: root
    group: root
    mode: 0640
  notify: restart supervisor
  tags: [configuration, supervisor, supervisor-configuration]

- name: update init script - /etc/init.d/supervisor
  template:
    src: etc/init.d/supervisor.j2
    dest: /etc/init.d/supervisor
    owner: root
    group: root
    mode: 0755
  notify: restart supervisor
  tags: [configuration, supervisor, supervisor-configuration]

- name: start and enable service
  service:
    name: supervisor
    state: started
    enabled: yes
  tags: [configuration, supervisor, supervisor-start-enable-service]
